### Homework 7 and Midterm Data Set

The dataset you will be working with contains 3 separate csv files. Please feel free to duplicate this project into your own space by creating an account linked to your existing GitHub account (or via another login method of your choice).

`EXAM_DATA_COMPANY.csv` contains information about various companies including an address, its market capitalization (or total dollar market value of a company's outstanding shares of stock), the country (and state/province) where this company is headquartered and its corresponding time zone, and the stock ticker symbol.

`EXAM_DATA_PERSON.csv` contains information about employees working at various companies. It includes personal identifying information such as name, email, address, and country of residence (and some demographic data, namely gender). Financial-related information includes their social security number (SSN) and their payroll accounts (which are paid out using Bitcoin, hence the bitcoin addresses). Company-related information includes the employees official start date/time (when they were entered into the system), and the department in which they work. 

`EXAM_DATA_TRANSACT.csv` includes a list of transactions (or rather reimbursments) claimed by various individual's accounts. It includes details such as the time the transaction took place, including the time zone and corresponding Coordinated Universal Time (UTC) offset (side note: these do not match real life; just use what is given). The purchase category and name of the application used to conduct the transaction are also listed.

In [42]:
import pandas as pd
import numpy as np

company_df = pd.read_csv('EXAM_DATA_COMPANY.csv')
person_df = pd.read_csv('EXAM_DATA_PERSON.csv')
transact_df = pd.read_csv('EXAM_DATA_TRANSACT.csv')

In [43]:
#EXAM_DATA_COMPANY.csv contains information about various companies including an address, its market capitalization (or total dollar market value of a company's outstanding shares of stock), the country (and state/province) where this company is headquartered and its corresponding time zone, and the stock ticker symbol.
company_df.head(2)

,address,company,market_cap,industry,state,country,country_code,stock_symbol,time_zone
0,74409 La Follette Hill,Botsford-Dooley,$3.32B,Oil Refining/Marketing,NaN,Taiwan,TW,BCO,Asia/Taipei
1,4 Kropf Crossing,"Buckridge, Conroy and Nitzsche",$93.98M,Major Pharmaceuticals,NY,United States,US,CTIC,America/New_York

In [44]:
#EXAM_DATA_PERSON.csv contains information about employees working at various companies. It includes personal identifying information such as name, email, address, and country of residence (and some demographic data, namely gender). Financial-related information includes their social security number (SSN) and their payroll accounts (which are paid out using Bitcoin, hence the bitcoin addresses). Company-related information includes the employees official start date/time (when they were entered into the system), and the department in which they work.
person_df.head(2)

,first_name,last_name,email,gender,suffix,title,address,department,bitcoin_address,company,ssn,employee_start,country_code
0,Weber,Massenhove,wmassenhove0@about.com,M,NaN,Dr,98557 2nd Pass,Services,1Ken4CZmWgkghXJzCjHndpmEUMDtXPnUNp,"Lehner, Willms and McClure",527-63-1710,2021-02-02 03:48:49,ID
1,Grethel,Boyce,gboyce1@etsy.com,F,II,Rev,7 Marcy Lane,Accounting,18c1EisbFW7PrRyXoZcztY2oRUuUcnJ2hK,"Boehm, VonRueden and Turner",696-71-8117,2020-09-17 01:27:03,US

In [45]:
#EXAM_DATA_TRANSACT.csv includes a list of transactions (or rather reimbursments) claimed by various individual's accounts. It includes details such as the time the transaction took place, including the time zone and corresponding Coordinated Universal Time (UTC) offset (side note: these do not match real life; just use what is given). The purchase category and name of the application used to conduct the transaction are also listed.
transact_df.head(2)

,bitcoin_address,amount,date,time,time_zone,purchase_app,category,time_offset
0,13q3QxRNsksDNdVhRJnQMb8WLxnH2RqW4A,"€8605,56",19-Oct-2020,11:12:56 PM,Europe/Warsaw,Stim,Music,10.0
1,1HDSWNybswRtsFFGLFxAQrRzkvssT3NNaR,"€2019,11",28-Dec-2020,9:43:06 PM,Asia/Shanghai,Treeflex,NaN,-3.0

1. During which hour are there the most transactions? Be sure to take the time zone into consideration (i.e. report everything relative to UTC+0 for instance).

In [46]:
#establish which csvfile to use

#change date and time to date time format and place as index

In [47]:
# def transaction_hour(df):
#     df['datetime'] = pd.to_datetime(df['date'] + ' ' + df['time'])
#     df.drop('date', inplace=True, axis = 1)
#     df.drop('time', inplace=True, axis = 1)
#     df['UTC_time'] = (df['time_offset'] + df['datetime'].dt.hour) % 24
#     #df = df.sort_values(df['UTC_time'], ascending = False)
#     return df



# transaction_hour(transact_df).head()

2. Generate a list of all individuals working for pharmaceutical companies that have a market capitalization with units measured in the billions.

In [48]:
#establish which dataframe to use = person_df and company_df
#merge dataframes
mergedf = pd.merge(person_df, company_df, how = 'inner', on=['company', 'country_code'])

#dataframe where only industry is Major Pharmaceuticals
pharmadf = mergedf[mergedf['industry'] == 'Major Pharmaceuticals']

#create a new column deciding who has billions and who doesn't
import re
def billions(row):
    pattern = r'\$\d.\d+B'
    results = re.findall(pattern, row['market_cap'])
    if results:
        return True
    return False
pharmadf['billions'] = pharmadf.apply(billions, axis = 1)

#isolate the rows that have billions as True
pharmadf = pharmadf[pharmadf['billions'] == True]

#isolate the names
pharmadf[['first_name', 'last_name']]

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()

    first_name last_name
154     Shayne   Statton

3. What is the monthly average number of transactions (processed in Euros) for each purchase app in the transactions dataset? Which app has the - (1) all-time highest, and (2) all-time lowest number of unique users?

In [49]:
transact_df.head()

,bitcoin_address,amount,date,time,time_zone,purchase_app,category,time_offset
0,13q3QxRNsksDNdVhRJnQMb8WLxnH2RqW4A,"€8605,56",19-Oct-2020,11:12:56 PM,Europe/Warsaw,Stim,Music,10.0
1,1HDSWNybswRtsFFGLFxAQrRzkvssT3NNaR,"€2019,11",28-Dec-2020,9:43:06 PM,Asia/Shanghai,Treeflex,NaN,-3.0
2,12kiq1UUw6aBgnGZBMFZaW7hDbH51uA4A6,"€9984,66",26-Nov-2020,5:56:19 PM,Asia/Harbin,Konklab,Industrial,4.0
3,1EXyq8wdLhZcDECocKDGZ7aCq6RmETeYJb,"€5709,95",03-Jun-2020,7:38:22 PM,Asia/Tehran,Otcom,Beauty,-4.0
4,15mp1C8hQeZ8gU5cqT61YBevptAtsjdWZQ,£5149.41,18-Sep-2020,8:57:58 PM,Europe/Kiev,Veribet,NaN,2.0

In [54]:
#isolate dataframe to use = transact_df
#isolate amounts that use euros
import re
euros_df = transact_df[(transact_df['amount'].str.match(r'€.+') == True)]

#change index to datetime
euros_df['datetime'] = pd.to_datetime(euros_df['date'] + ' ' + euros_df['time'])
euros_df = euros_df.set_index('datetime').drop(['date', 'time'], axis = 1)

#next we must resample to month


avg_num = euros_df.groupby('purchase_app')


avg_num.head()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,bitcoin_address,amount,time_zone,purchase_app,category,time_offset
datetime,,,,,,
2020-10-19 23:12:56,13q3QxRNsksDNdVhRJnQMb8WLxnH2RqW4A,"€8605,56",Europe/Warsaw,Stim,Music,10.0
2020-12-28 21:43:06,1HDSWNybswRtsFFGLFxAQrRzkvssT3NNaR,"€2019,11",Asia/Shanghai,Treeflex,NaN,-3.0
2020-11-26 17:56:19,12kiq1UUw6aBgnGZBMFZaW7hDbH51uA4A6,"€9984,66",Asia/Harbin,Konklab,Industrial,4.0
2020-06-03 19:38:22,1EXyq8wdLhZcDECocKDGZ7aCq6RmETeYJb,"€5709,95",Asia/Tehran,Otcom,Beauty,-4.0
2020-11-19 18:32:20,1GMonRgcncJDFmYUtZVzqQYKneVscAQ1Fc,"€6005,33",Europe/Belgrade,Aerified,NaN,-5.0
2020-03-09 05:51:48,1Pd4iujMZnynAGa8UACJzfUepfdrfPjazD,"€5775,27",Africa/Johannesburg,Stringtough,Outdoors,-6.0
2020-07-16 07:37:33,1MPvv9jF1LN9TvVf5qm9QMkfY3BgUo55aQ,"€3315,48",Europe/Sofia,Rank,Automotive,3.0
2020-06-15 05:46:10,1rQwgY5Q2NykkjsTmmU6f6BswNzf7VJxq,"€5628,89",Africa/Niamey,Voyatouch,Jewelery,-5.0
2020-08-28 23:06:24,1J9GjTJ7fA8YJXHRwJJXyXQAbbScW4xk4u,"€3042,05",Asia/Baku,It,Baby,-7.0
2021-03-04 04:49:58,1ATRnsgY9qXChPLAjxWERCCxWCZ6tgS8Zb,"€2193,56",Europe/Vienna,Zamit,NaN,-6.0
2020-11-27 00:13:43,1NttLNueoDhW83Dk9jukz6N1GaBAHMKUWP,"€9345,31",Asia/Almaty,Prodder,NaN,8.0
2020-04-06 16:20:13,1FPCB958z6vxrkWUruHjPHLQu3FqM9jGYH,"€8924,08",Asia/Makassar,Bitwolf,Outdoors,-8.0
2020-08-15 20:14:28,1G3YhuWgUpWZJ6FnffkFXnYWhfUpmYPjmC,"€3408,68",Europe/Oslo,It,NaN,5.0
NaT,14A7xJxWgMatvjzpDGBDxKwLkdEimv4T8f,"€3770,05",Asia/Shanghai,Fix San,Books,-3.0
2020-08-29 23:01:41,1LhaFVTknpitRDYXd9MqRG2sCQUf7m3MHd,"€8942,74",Asia/Chongqing,Voltsillam,Music,2.0
2021-02-05 21:17:14,18xrGzvBuSxGtaYeWNjiRzQn1qfW7giaXY,"€5960,37",Asia/Urumqi,Trippledex,Games,-7.0
2021-01-24 19:16:06,19w8vfFgZfEGQe5pJMA1PqWmyPDiP6tujk,"€8609,97",Africa/Lagos,Job,NaN,11.0
2020-12-10 10:22:30,15zNYn8qP2cSR5A7hbm7ai8Wbm5ehMTWTX,"€2995,36",Atlantic/Cape_Verde,Sonair,Movies,-10.0
2020-07-18 03:29:22,114omuQEmEgLj8PehpCvJyQ5ddGjE6zKtq,"€6283,44",Europe/Paris,Redhold,Baby,-6.0
2020-03-27 22:47:01,12D2ZXnNqjM7MtJ6kS5JpAYQoBZhwfuHJT,"€4185,92",America/Bogota,Y-Solowarm,Music,-7.0
2020-05-04 06:52:12,1Cksrmz11oADH6F2nK4NF6Mkbz8FhhghN1,"€8786,19",Europe/Zurich,Fix San,NaN,-5.0
2020-11-12 03:28:58,1JiCnq4Rr6DpgzuTznZ6Lek8Sbf7mqMkNa,"€3709,64",Asia/Manila,Zoolab,NaN,-6.0
2020-04-16 21:14:31,16yGYfj2FAdFk3KxA52FREDzRjzvHWSMa3,"€4341,98",Europe/Uzhgorod,Lotstring,Industrial,-1.0
2020-06-06 15:38:49,1LtYQuDJ1aSv2hGgAY1KjqY53WwFeo5Vk8,"€9914,36",Asia/Amman,Voltsillam,NaN,9.0
2021-03-04 18:21:56,1JiCnq4Rr6DpgzuTznZ6Lek8Sbf7mqMkNa,"€4170,98",Asia/Jakarta,Konklab,Movies,10.0
2020-08-14 20:44:39,12Wg9evS5LtDSHJawo1qRiogdoQx6DEsDj,"€8412,09",Asia/Shanghai,Lotlux,Movies,-3.0
2021-01-01 15:00:59,1KUcVfRVnLhRxSitsEpRKd7G2fmfZEr6Rg,"€167,03",Asia/Macau,Holdlamis,Shoes,-2.0
2020-11-25 08:54:23,12ZBiCVh5URVWsfV3Kcp8QN9HUWdQdQ45W,"€1969,49",Asia/Jakarta,Veribet,Baby,10.0
2020-05-18 04:12:36,1NttLNueoDhW83Dk9jukz6N1GaBAHMKUWP,"€1640,62",Asia/Jakarta,Greenlam,Games,10.0
2021-02-08 06:03:32,1G835v3hj1R3ytDXzBJnNE7mBwv5PUK7L,"€2250,78",Asia/Pontianak,Voltsillam,NaN,-4.0
...,...,...,...,...,...,...
2020-06-11 07:50:08,1PxKQya51vbtV21fRpbBXnukGbJpASe5kL,"€8083,15",America/Los_Angeles,Toughjoyfax,Kids,-3.0
2020-05-06 06:47:14,1L9kUfhe5E25xSjfhtbjTKLbC98VVAWbXG,"€4539,46",America/Detroit,Tempsoft,Clothing,3.0
2021-01-23 08:32:31,1DQ8hnHMR65VejAeQk8aUiFQqm666y6p7a,"€3682,61",Europe/Lisbon,Holdlamis,Electronics,2.0
2021-01-27 22:25:34,1ErnnrFCtQvCqQc66UqhFhM8HBy4nSragG,"€5012,85",Europe/Oslo,Quo Lux,Clothing,5.0
NaT,1AVpsXdWRbsAQ3m8ma1xoHiJSQFyVuzNf2,"€6932,53",Asia/Manila,Y-find,Industrial,-6.0
2021-02-17 22:06:16,15mp1C8hQeZ8gU5cqT61YBevptAtsjdWZQ,"€744,28",America/Mexico_City,Asoka,NaN,-2.0
2020-09-06 16:08:19,1JGZsf2KNgrvtmNeY6mDx4gnfo1QbGwaH,"€9399,85",Asia/Jakarta,Wrapsafe,Automotive,10.0
2020-11-06 11:49:40,1Bs2kpyV2mkEwaAdsdC4uELkELzfB9xHxQ,"€1906,96",Europe/Amsterdam,Span,Jewelery,-7.0
NaT,1N39ohjUVhB7Zabo7V2CiLWuaturfuqNQ6,"€7287,19",Asia/Hebron,Asoka,Computers,9.0
2020-12-01 23:34:11,17h1HP6Hkmt9sgoB3ha721faTEFmMkSkRZ,"€1584,82",Asia/Makassar,Asoka,Baby,-8.0
2020-12-09 20:37:27,13VtrCcfZB9QQRb731QtLT2AU8VtfJVPid,"€8796,47",Asia/Tokyo,Regrant,Grocery,9.0
2020-09-03 08:05:00,1MmGWy8wg8fEvL4AsnKw6WiXc2d7RRaW8w,"€103,72",Europe/Riga,Sonair,Sports,1.0
2020-11-30 01:24:57,1P9bbiBLQ22Fhkkc2yBTH3kae1PKWVPeEY,"€3682,98",Asia/Manila,Sonair,Industrial,-6.0
2020-08-02 08:55:20,1FNgafogQv2hcYc5dpwvUkstMaLnaPiS98,"€4683,86",America/Bogota,Tempsoft,Books,-7.0
2021-01-01 11:47:31,1N3SpBv4RDG6mf5EjDLUbtA3JPViYUxw3g,"€2875,86",Europe/Zaporozhye,Cardify,Tools,11.0
NaT,1Hm25Afv2uDMpWsHKBx91yLFSe6QwEMYaF,"€3580,84",Europe/Warsaw,Lotlux,NaN,10.0
2021-01-17 11:53:06,1D8pT5UiFmmqsGR7HCk984GidHPnTn6Bpx,"€7898,09",Pacific/Tahiti,Stringtough,Baby,-1.0
2020-08-20 10:51:02,16kan1K5vRJxqQFzruKHAvznV6Xfbh59w,"€2680,50",Asia/Ulaanbaatar,Bitwolf,NaN,3.0
2020-06-01 05:20:31,18Nmj7uDsS4dr5rN55Qw7fuxmBCLmFhvwN,"€2793,49",Asia/Urumqi,It,Games,-7.0
2020-12-28 07:14:15,1MSzLPN6WuRpjeJUYSf73Myqy3TU6SNLc2,"€2119,94",Asia/Shanghai,Span,Movies,-3.0
2020-04-13 05:46:39,1B6C9pFXRSxFL5agh87zFAUrWJrJHvKCmo,"€1156,01",America/Sao_Paulo,Lotlux,NaN,-4.0
2020-10-21 14:13:36,138eKhaJ9hYPLDvaWXEWZVfbdmpMRBp6nk,"€1002,94",America/Guayaquil,Zaam-Dox,Garden,6.0
2020-11-17 10:53:52,1FsYEber3L11W7UWSrtbGrzNuzTxt9xQa8,"€6504,66",Europe/Luxembourg,Stim,Computers,-4.0
NaT,1QJ2bF8h2QLB7mVk2gkp3hoxcFdR5AYV75,"€5885,59",Asia/Bangkok,Job,Movies,7.0
2021-01-06 08:56:41,16kvgpcFGLipQphodCDy22g4pkkoX585ds,"€685,14",Europe/Paris,Subin,Health,-6.0
2020-08-31 12:48:56,1Len4LzJ8JYd37hGxE3ru6zQM4xoAmp4Dr,"€9270,27",Africa/Luanda,Job,Health,-11.0
NaT,1MGP31dRA2SwBeCoqYgS9d6AJjjViGwpfU,"€5751,30",Europe/Lisbon,Wrapsafe,Kids,2.0
2020-10-27 02:21:31,1NeVkfGuvsh2QdggwDve93Cb8ipgUhaUfA,"€3072,09",America/Bahia,Konklux,Kids,-8.0
NaT,16EiidiFKefVNK7NeG42S7uL39JKx7yvbu,"€1057,20",Asia/Jakarta,Latlux,Sports,10.0
2020-10-07 11:31:51,12VrC5atYzdAJjzyZXQ7GxeyxCi56bZw71,"€238,15",Asia/Kuala_Lumpur,Treeflex,Garden,-3.0

In [ ]:
def avg_transaction(df):
    #df = pd.merge
    #df = df.set_index(pd.to_datetime(df['date']))
    #df.drop('date', inplace = True, axis = 1)
    df = df[(df['amount'].str.match(r'€.+') == True)]
    df['date'] = df['date'] + ' ' + df['time']
    #df['date'] = pd.to_datetime(df['date'])
 
    return df


avg_transaction(transact_df).head()

4
In the file containing information on employees, there are some inconsistencies with column 'title'. 
Create a new column with each employee’s entire name formatted as follows: add a period to the end of 
each title to reflect that it is an abbreviation, and change each "Honorable" title to its proper abbreviation, "Hon." 
Lastly, don’t forget to tack on the suffix if applicable!

In [145]:
person_df.head()

,first_name,last_name,email,gender,suffix,title,address,department,bitcoin_address,company,ssn,employee_start,country_code
0,Weber,Massenhove,wmassenhove0@about.com,M,NaN,Dr,98557 2nd Pass,Services,1Ken4CZmWgkghXJzCjHndpmEUMDtXPnUNp,"Lehner, Willms and McClure",527-63-1710,2021-02-02 03:48:49,ID
1,Grethel,Boyce,gboyce1@etsy.com,F,II,Rev,7 Marcy Lane,Accounting,18c1EisbFW7PrRyXoZcztY2oRUuUcnJ2hK,"Boehm, VonRueden and Turner",696-71-8117,2020-09-17 01:27:03,US
2,Wilmar,Duester,wduester2@deliciousdays.com,M,NaN,Honorable,57666 Stoughton Court,Human Resources,1DuQgLuydME3HtXrYtDm6xk8agNqozhzs9,"Harris, Abbott and O'Kon",383-85-6348,2020-10-01 01:30:20,US
3,Marrilee,Burtt,mburtt3@nps.gov,F,Sr,NaN,074 Elgar Point,Research and Development,12jmLByL7ngA6TLpRPNAtuh7Src7LGhiKn,Feeney-Gusikowski,674-80-7976,2020-12-30 18:25:52,PT
4,Ava,Burchett,aburchett4@taobao.com,F,NaN,Honorable,76045 Mockingbird Crossing,Services,1FDyhoQmmcrHXCcWD4cMy7VJCankW1K9R3,"Kerluke, Langworth and Spinka",676-58-0954,2021-02-01 23:30:49,BR

In [56]:
#figure out which file to use = person_df
npdf = person_df

#add period to title column

#create column called full title
npdf['full_title'] = npdf[npdf.apply(npdf['title'] + '. ' + npdf['first_name'] + npdf['last_name'])]

AttributeError: 'Dr. WeberMassenhove' is not a valid function for 'Series' object

In [163]:
def import_df(df):
    df['new_name'] = df.apply(title_change)
    return df
    
def title_change(row):
    return row['title'] + '. ' + row['first_name'] + row['last_name']

import_df(person_df)

KeyError: ('title', 'occurred at index first_name')

5. incorrect solution

In [57]:
person_df.head()

,first_name,last_name,email,gender,suffix,title,address,department,bitcoin_address,company,ssn,employee_start,country_code
0,Weber,Massenhove,wmassenhove0@about.com,M,NaN,Dr,98557 2nd Pass,Services,1Ken4CZmWgkghXJzCjHndpmEUMDtXPnUNp,"Lehner, Willms and McClure",527-63-1710,2021-02-02 03:48:49,ID
1,Grethel,Boyce,gboyce1@etsy.com,F,II,Rev,7 Marcy Lane,Accounting,18c1EisbFW7PrRyXoZcztY2oRUuUcnJ2hK,"Boehm, VonRueden and Turner",696-71-8117,2020-09-17 01:27:03,US
2,Wilmar,Duester,wduester2@deliciousdays.com,M,NaN,Honorable,57666 Stoughton Court,Human Resources,1DuQgLuydME3HtXrYtDm6xk8agNqozhzs9,"Harris, Abbott and O'Kon",383-85-6348,2020-10-01 01:30:20,US
3,Marrilee,Burtt,mburtt3@nps.gov,F,Sr,NaN,074 Elgar Point,Research and Development,12jmLByL7ngA6TLpRPNAtuh7Src7LGhiKn,Feeney-Gusikowski,674-80-7976,2020-12-30 18:25:52,PT
4,Ava,Burchett,aburchett4@taobao.com,F,NaN,Honorable,76045 Mockingbird Crossing,Services,1FDyhoQmmcrHXCcWD4cMy7VJCankW1K9R3,"Kerluke, Langworth and Spinka",676-58-0954,2021-02-01 23:30:49,BR

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=4b899bc4-47db-49d1-afe8-5e169e10f438' target="_blank">
<img style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>

In [82]:
# def employees(person_df):
#     employees = person_df.groupby('department', axis = 1)
#     return employees

# #employees = person_df.groupby('department', axis = 1)#.loc['gender'].value_counts().to_frame(name = 'count').reset_index()

# #x.set_index('department')
# #x = employees[employees['gender'] == "F"]

# #print(x['count'].idxmax())
# employees(person_df.head())

In [84]:
employees = person_df#.groupby('department')
employees.head(3)

#.loc['gender']
# .value_counts()
# .to_frame(name = 'count')
# .reset_index()
 
# x = employees[gender] == "F"
# x.set_index('department')
# print(x['count'].idxmax())

,first_name,last_name,email,gender,suffix,title,address,department,bitcoin_address,company,ssn,employee_start,country_code
0,Weber,Massenhove,wmassenhove0@about.com,M,NaN,Dr,98557 2nd Pass,Services,1Ken4CZmWgkghXJzCjHndpmEUMDtXPnUNp,"Lehner, Willms and McClure",527-63-1710,2021-02-02 03:48:49,ID
1,Grethel,Boyce,gboyce1@etsy.com,F,II,Rev,7 Marcy Lane,Accounting,18c1EisbFW7PrRyXoZcztY2oRUuUcnJ2hK,"Boehm, VonRueden and Turner",696-71-8117,2020-09-17 01:27:03,US
2,Wilmar,Duester,wduester2@deliciousdays.com,M,NaN,Honorable,57666 Stoughton Court,Human Resources,1DuQgLuydME3HtXrYtDm6xk8agNqozhzs9,"Harris, Abbott and O'Kon",383-85-6348,2020-10-01 01:30:20,US